{{- if .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gonzalo.fullname" . }}-auth
  labels:
    {{- include "gonzalo.labels" . | nindent 4 }}
type: Opaque
stringData:
  GONZALO_TOKEN: {{ .Values.auth.token | quote }}
{{- end }}
