{{- if and (eq .Values.topology "clustered") .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "prospero.fullname" .) }}
  labels:
    {{- include "prospero.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.url | quote }}
{{- end }}
